[package]
name = "goji"
version = "0.1.0"
authors = ["softprops <d.tangren@gmail.com>"]
description = "Rust interface for Jira"
documentation = "http://softprops.github.io/goji"
homepage = "https://github.com/softprops/goji"
repository = "https://github.com/softprops/goji"
keywords = ["hyper", "jira"]
license = "MIT"
build = "build.rs"

[dev-dependencies]
env_logger = "0.3"

[dependencies]
log = "0.3"
hyper = "0.9"
rustc-serialize = "0.3"
url = "1.1"
serde = "0.7"
serde_json = "0.7"

[build-dependencies]
serde_codegen = "0.7"
syntex = "0.29"