[package]
name = "goji"
version = "0.1.1"
authors = ["softprops <d.tangren@gmail.com>"]
description = "Rust interface for Jira"
documentation = "http://softprops.github.io/goji"
homepage = "https://github.com/softprops/goji"
repository = "https://github.com/softprops/goji"
keywords = ["hyper", "jira"]
license = "MIT"

[dev-dependencies]
env_logger = "0.3"

[dependencies]
hyper = "0.9"
log = "0.3"
serde = "0.9"
serde_derive = "0.9"
serde_json = "0.9"
url = "1.2"
