[package]
name = "goji"
version = "0.2.0"
authors = ["softprops <d.tangren@gmail.com>"]
description = "Rust interface for Jira"
documentation = "http://softprops.github.io/goji"
homepage = "https://github.com/softprops/goji"
repository = "https://github.com/softprops/goji"
keywords = ["hyper", "jira"]
license = "MIT"
readme = "README.md"

[badges]
travis-ci = { repository = "softprops/goji" }
maintenance = { status = "actively-developed" }

[dev-dependencies]
env_logger = "0.4"

[dependencies]
log = "~0.3"
reqwest = "~0.7"
serde = "1.0.15"
serde_derive = "1.0.15"
serde_json = "1.0.3"
url = "~1.5"
